//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace varai2d_surface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Sett_mainpic {
            get {
                return ((global::System.Drawing.Color)(this["Sett_mainpic"]));
            }
            set {
                this["Sett_mainpic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlueViolet")]
        public global::System.Drawing.Color Sett_member_clr {
            get {
                return ((global::System.Drawing.Color)(this["Sett_member_clr"]));
            }
            set {
                this["Sett_member_clr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color Sett_point_clr {
            get {
                return ((global::System.Drawing.Color)(this["Sett_point_clr"]));
            }
            set {
                this["Sett_point_clr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color Sett_snapline_clr {
            get {
                return ((global::System.Drawing.Color)(this["Sett_snapline_clr"]));
            }
            set {
                this["Sett_snapline_clr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSeaGreen")]
        public global::System.Drawing.Color Sett_stringfore_clr {
            get {
                return ((global::System.Drawing.Color)(this["Sett_stringfore_clr"]));
            }
            set {
                this["Sett_stringfore_clr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Sett_member_width {
            get {
                return ((int)(this["Sett_member_width"]));
            }
            set {
                this["Sett_member_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Sett_point_radius {
            get {
                return ((int)(this["Sett_point_radius"]));
            }
            set {
                this["Sett_point_radius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Sett_snapline_width {
            get {
                return ((int)(this["Sett_snapline_width"]));
            }
            set {
                this["Sett_snapline_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_horiz_vert_snap {
            get {
                return ((bool)(this["Sett_horiz_vert_snap"]));
            }
            set {
                this["Sett_horiz_vert_snap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_point_snap {
            get {
                return ((bool)(this["Sett_point_snap"]));
            }
            set {
                this["Sett_point_snap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Sett_horiz_vert_intensity {
            get {
                return ((double)(this["Sett_horiz_vert_intensity"]));
            }
            set {
                this["Sett_horiz_vert_intensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double Sett_point_intensity {
            get {
                return ((double)(this["Sett_point_intensity"]));
            }
            set {
                this["Sett_point_intensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_is_paint_pt {
            get {
                return ((bool)(this["Sett_is_paint_pt"]));
            }
            set {
                this["Sett_is_paint_pt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sett_is_paint_ptcoord {
            get {
                return ((bool)(this["Sett_is_paint_ptcoord"]));
            }
            set {
                this["Sett_is_paint_ptcoord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_is_paint_ptid {
            get {
                return ((bool)(this["Sett_is_paint_ptid"]));
            }
            set {
                this["Sett_is_paint_ptid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_is_paint_memid {
            get {
                return ((bool)(this["Sett_is_paint_memid"]));
            }
            set {
                this["Sett_is_paint_memid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_is_paint_memlength {
            get {
                return ((bool)(this["Sett_is_paint_memlength"]));
            }
            set {
                this["Sett_is_paint_memlength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public string Sett_coord_pres {
            get {
                return ((string)(this["Sett_coord_pres"]));
            }
            set {
                this["Sett_coord_pres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public string Sett_length_pres {
            get {
                return ((string)(this["Sett_length_pres"]));
            }
            set {
                this["Sett_length_pres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sett_is_paint_surfid {
            get {
                return ((bool)(this["Sett_is_paint_surfid"]));
            }
            set {
                this["Sett_is_paint_surfid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Sett_font_size {
            get {
                return ((int)(this["Sett_font_size"]));
            }
            set {
                this["Sett_font_size"] = value;
            }
        }
    }
}
